import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import State from "@/app/Context/State";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sight Shark Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <State>{children}</State>
      </body>
    </html>
  );
}
