name: Deploy Next.js to GCP

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to GCP
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.GCP_INSTANCE_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.SSH_USERNAME }}/admin-portal-frontend/client
          git pull origin main
          npm install
          npm run build
          sudo systemctl restart nextjs
